### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by wootwoot1234** [fsboehme/intercom-gpt-bot#1]
I just came across this project and I’m super excited to use it.  I wanted to check if you're using this in production and what the quality if the responses have been?

Just an idea but it would be cool to have the option to post the response as a note instead of a message so that we can see the responses without sending them. Then copy and paste them as needed.

**Comment by fsboehme** [comment]
Thanks! That's actually how I'm using it right now. The TEST_MODE env var let's you control that. I've not set it live yet to reply directly with messages myself since it's not super reliable yet. I'm trying to get it to use the article sections more verbatim. It's freestyling a bit too much still... Tweaking the prompt and optimizing my articles. It probably depends to a large degree on the quality of your articles and how well they're structured to break down into sections by headings. I bet gpt-4 could also do a better job, since you could give it more context. I don't have access to that yet, sadly.

**Comment by wootwoot1234** [comment]
Cool, I'm happy to hear you're using it. I’ll try to set it up and see if I can help out. I'm not a Python developer but maybe I can help with the docs 😂

I'm using the openai API in another project and had similar issues with it giving inaccurate/wild results. I need to look at the code again but I think I set the `temperature` to 0 and it helped a lot.

**Comment by wootwoot1234** [comment]
Yeah, try setting `temperature: 0.0`

**Comment by wootwoot1234** [comment]
I set it up and got this error when I wrote a message:

```
[2023-04-25 06:17:25,256] ERROR in app: Exception on request POST /webhook
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/quart/app.py", line 1553, in _wrapper
    await copy_current_app_context(self.ensure_async(func))(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/quart/ctx.py", line 343, in wrapper
    return await app_context.app.ensure_async(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/HostTools/intercom-gpt-bot/intercom_webhook.py", line 63, in process_webhook
    conversation_id, messages = await prep_conversation(item)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/HostTools/intercom-gpt-bot/intercom_webhook.py", line 83, in prep_conversation
    user_name = AUTHOR_LABELS.get(item["conversation_message"]["author"]["type"])
                                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversation_message'
```

This is the data that was sent:
```json
{
    "type":"conversation",
    "id":"30392",
    "created_at":1682421119,
    "updated_at":1682421442,
    "waiting_since":1682421119,
    "snoozed_until":"None",
    "source":{
       "type":"conversation",
       "id":"1644338",
       "delivered_as":"customer_initiated",
       "subject":"",
       "body":"<p>Do I have to use the host only fee if I'm a customer of yours?</p>",
       "author":{
          "type":"user",
          "id":"6064e4337422e1ab",
          "name":"Jack Frost",
          "email":"jackfrost99@gmail.com"
       },
       "attachments":[
          
       ],
       "url":"https://example.com/",
       "redacted":false
    },
    "contacts":{
       "type":"contact.list",
       "contacts":[
          {
             "type":"contact",
             "id":"6064e4337422e1ab"
          }
       ]
    },
    "first_contact_reply":{
       "created_at":1682421119,
       "type":"conversation",
       "url":"https://example.com/"
    },
    "admin_assignee_id":"None",
    "team_assignee_id":"None",
    "open":true,
    "state":"open",
    "read":true,
    "tags":{
       "type":"tag.list",
       "tags":[
          
       ]
    },
    "priority":"not_priority",
    "sla_applied":"None",
    "statistics":{
       "type":"conversation_statistics",
       "time_to_assignment":"None",
       "time_to_admin_reply":"None",
       "time_to_first_close":"None",
       "time_to_last_close":"None",
       "median_time_to_reply":"None",
       "first_contact_reply_at":"2023-04-25T11:11:59.000Z",
       "first_assignment_at":"None",
       "first_admin_reply_at":"None",
       "first_close_at":"None",
       "last_assignment_at":"None",
       "last_assignment_admin_reply_at":"None",
       "last_contact_reply_at":"2023-04-25T11:17:22.000Z",
       "last_admin_reply_at":"None",
       "last_close_at":"None",
       "last_closed_by_id":"None",
       "count_reopens":0,
       "count_assignments":0,
       "count_conversation_parts":4
    },
    "conversation_rating":"None",
    "teammates":{
       "type":"admin.list",
       "admins":[
          
       ]
    },
    "title":"",
    "custom_attributes":{
       
    },
    "topics":{
       
    },
    "conversation_parts":{
       "type":"conversation_part.list",
       "conversation_parts":[
          {
             "type":"conversation_part",
             "id":"21216248487",
             "part_type":"comment",
             "body":"<p>Do I have to use the host only fee if I'm a customer of yours?</p>",
             "created_at":1682421442,
             "updated_at":1682421442,
             "notified_at":1682421442,
             "assigned_to":"None",
             "author":{
                "id":"6064e4337422e1ab",
                "type":"user",
                "name":"Jack Frost",
                "email":"jackfrost99@gmail.com"
             },
             "attachments":[
                
             ],
             "external_id":"None",
             "redacted":false
          }
       ],
       "total_count":1
    }
 }
```

**Comment by wootwoot1234** [comment]
It worked great after I changed `item["conversation_message"]` to `item["source"]`.

**Comment by fsboehme** [comment]
oh, yeah, just noticed that my API version was 1.4. updated it and made that change.
